### ISSUE TITLE
Download source from github

### ISSUE THREAD

**Issue by Adurol** [KaOS-Community-Packages/aftl#1]
Instead of using git to clone a specific commit (and have `git` as makedepend) from github, it is better to download the zip-file of the wanted commit. Using git to build a package should be avoided if can for KCP. If you want to know how this can be done, look f.e. at [xclip](https://github.com/KaOSx/apps/blob/master/xclip/PKGBUILD).

Adding the commit-hash to to version number is not preferred on KCP. For this cases, just add minor-numbers. Demm mentioned it [here](https://forum.kaosx.us/d/1793-help-with-pkgbuild-variables-for-android-file-transfer-linux) already.

If you change something in the functions, and the version number stays the same, increase pkgrel. In de7324f8a609c04adeea65cc7fa0297fb4cc58e9 both functions and pkgver even changed for the same version. (And did you test if this doesn't cause a downgrade conflict? There is `vercmp` to test this.)

**Comment by keijukainen** [comment]
I had no idea you could download specific commits as zip files.  Thanks for the tip.

I originally had .70 included in the version but I wanted a way to associate each package with the git commit that it's built from.  The Arch repo uses this version method so I thought it would be safe to use here.  They also frequently include "-git" in the package name if it's built from a git repo.

**Comment by keijukainen** [comment]
I wasn't familiar with the vercmp tool.  I just tested it with a few different examples and I'm slightly confused regarding the versioning system in KCP.  If we use .70/alpha, .80/beta, etc., then the final release is always going to appear older than the alpha/beta/rc.

`vercmp 3.1 3.1.70`

Returns -1 so if I'm understanding this correctly that means that 3.1 will appear to be older than 3.1.70.  In the case of aftl, the developer has bumped the version to 3.1 but it's still in either alpha or beta stage.  So I need to affix .70 to the version.  Once it's officially released the .70 would be removed but the package would appear to be older than the 3.1.70 version.  So how is it possible to avoid a downgrade conflict in this scenario?

**Comment by Adurol** [comment]
> I had no idea you could download specific commits as zip files. Thanks for the tip.

Github offers quite a few nice things on the side 😉 

> The Arch repo uses this version method so I thought it would be safe to use here. They also frequently include "-git" in the package name if it's built from a git repo.

Arch offers quite good docs for building packages with pacman. But some things here (KCP) are a bit different then on AUR. On KCP, there will be no "-git" packages. Reason is, that you don't have control over what version the user installs. (In this case yous set a specific commit to do the same. But then, github provides a zip for ever commit, so it's also nice to get a hashsum for it, and not skip it.)

You would use .70/80/90 *before* the next minor release. So, if the last release is x.5, and you expect that the next release will be x.6, then you can do something like x.5.70. If the release will become x.5.1, then you can do x.5.0.70. That's how I would do it. The thinking is more like "I'm ahead of the latest (official) release, but before the next (official) release". Most times there is a pattern how the developer numbers the versions. (And if everything goes wrong, there is always `epoch=`.)

How I see it, the latest version of aftl is v3.0. So naming you PKGBUILD with 3.1 is fundamentally wrong, as it would conflict with the official release v3.1 anyway. (Your PKGBUILD can't be v3.1, as it isn't even released yet.)

**Comment by keijukainen** [comment]
I updated the PKGBUILD with your recommendations (haven't committed it yet).  Unfortunately since 3.1 was previously used I have to use epoch to mark this package as newer.  I used pkgrel=3 since this is my third upate.  Let me know if you spot any errors.  Thanks.
[diff.txt](https://github.com/KaOS-Community-Packages/aftl/files/728294/diff.txt)

**Comment by Adurol** [comment]
You can just use `pkgrel=1` for the new PKGBUILD with `epoch=1`, as no predecessor has been pushed to KCP (it's just like if you would push a new version, then you reset `pkgrel` too).

Tipp: instead of linking to a diff, just fork the repo and open a pull request. That way github shows a nice diff and commenting on pull request is also possible. (And also, pull requests can be "updated" with further improvements along with the discussion.)

**Comment by keijukainen** [comment]
PKGBUILD is updated.
